import 'package:flutter/painting.dart';
import 'package:flutter/material.dart';
import 'package:national_digital_notes_new/views/main/utils/AppColors.dart';
class ColorValues {
  static const Color SIGIN_TITLE_COLOR = const Color(0xFFb3be85);
  static const Color YELLOW = const Color(0xFFFEBD0B);
  static const Color BORDER_COLORE = Colors.blue;
  static const Color SLIDER_BACKGROUND_COLOR = const Color(0xFFF2F2F2);
  static const Color NOTIFICATION_BLUE = const Color(0xFF004AD7);
  static const Color BG_TYPE = const Color(0xFF2d2d2d);
  static const Color BLACK = const Color(0xFF000000);
  static const Color BG_BT2 = const Color(0xFFff2f2f);
  static const Color LOGOUT_TEXT = const Color(0xFFF9016B);
  static const Color BG_ORDER = const Color(0xFFB4bd84);
  static const Color BUTTON_COLOR = const Color(0xFF71af3e);
  static const Color DIVIDER_COLOR = const Color(0xFFBBBBBB);
  static const Color PAYMENT_OPTION_BACK = const Color(0xFFF8F7FA);
  static const Color TIME_NOTITFICAITON = const Color(0xFF949494);
  static const Color TEXT_COLOR = const Color(0xFF080255);
  static const Color CALL_COLOR = const Color(0xFF23D61F);
  static const Color HINT_TEXT_COLOR = const Color(0xFF3F3D56);
  static const Color BACKGROUND = const Color(0xff00F9FF);
  static const Color TEXT_SENT_OTP_COLOR = const Color(0xFF6D6d6D);
  static const Color GREY_BORDER_COLOR = const Color(0xFFD0DBDF);

   static const int NAVIGATION_DRAWER_BG_COLOUR = 0XFFF7F7F9;
  static const int BOTTOAMBAR_ADD_BG_COLOUR= 0XFF3C79DB;
  static const int HOME_TEXT_COLOUR= 0XFF606062;
  static const int HOME_BG_COLOUR= 0XFFf7f7f8;
  static const int BUTTON_TEXT_GRAY = 0xFF97a3b2;
  static const int BUTTON_TEXT_BLUE = 0xFF5185e8;
  static const int BUTTON_LOGIN_BG = 0xFFf8f9fb;
//  static const int BLUE_COLOR = 0xFF3B79E0;
  static const int BLUE_COLOR = 0xFF4684EB;
  static const int BLUE_COLOR_BOTTOMBAR = 0xFF4684EB;
  static const int HEADING_COLOR = 0xFFC1E3FC;
  static const int HEADING_COLOR_EDUCATION = 0xFF151515;
  static const int SCREEN_BG_COLOR= 0xFFFAFAFA;
  static const int GREY_TEXT_COLOR= 0xFF404040;
  static const int LIGHT_GREY_TEXT_COLOR= 0xFFE9E9EC;
  static const int RADIO_BLACK= 0xFF151515;
  static const int GRAY_HEADER_PRESSO_VIEW = 0xffCACACA;
  static const int GRAY = 0xffCACACA;
  static const int LIGHT_GRAY_BG= 0xffF8F9F8;
  static const int OPPORTUNITY_GROUP_SELECTION_GRP = 0xffF0F0F0;
  static const int GRAY_BG = 0xffF8F8F8;

  static const int DEVIDER_COLOR = 0xffE9E9EC;
  static const int DARK_GREY = 0xffDEDEDE;
  static const int BORDER_COLOR = 0xffDEDEDE;
  static const int BG_CIRCLE_COLOR = 0xffA0A0A0;
  static const int WHITE = 0xffffffff;
  static const int RED = 0xffFD0000;
  static const int SELECTION_GRAY = 0xffF0F0F0;
  static const int SEARCH_CATEGORY_BOX_BG = 0xffC1E3FC;
  static const int SEARCH_CATEGORY_BOX_BG_SELCTED = 0xff4684EB;

  static const int BLACK_TEXT_COL = 0xFF707070;
  static const int THEME_TEXT_COLOR = 0xFF21C8BE;
  static const int UNSELECTED_TAB_COLOR = 0xFF707070;
  static const int TEXT_COL_GREY = 0xFF707070;
  static const int GRADIENT_COL_1 = 0xFF21C8BE;
  static const int GRADIENT_COL_2 = 0xFF036F68;
  static const int DIVIDER_COL = 0xFF262626;
  static const int BLACK_COL = 0xFF000000;
  static const int BOOKING_DATE_COL = 0xFFB1AEAE;
  
  static const int THEME_COLOR=0xff21C8BE;
  static const int WHITE_COLOR=0xffFFFFFF;
  static const int BLACK_COLOR = 0xFF000000;
  static const int GREY = 0xFF707070;
  static const int LIGHT_GRAY= 0xffF9F8F8;
  static const int DATE_BG=0xffF9F9F9;
  static const int LIGHT_TEXT_COLOR=0xff767676;
  static const int CELL_COLOR=0xff1D2A4D;
  static const int HINT_COL = 0xffBDBDBD;
}