


name: national_digital_notes_new
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.4
  flutter_svg: ^1.1.5
  get: ^4.6.5
  http: ^0.13.5
  circular_countdown_timer: ^0.2.2
  carousel_slider: ^4.1.1
  dots_indicator: ^2.1.0
  confetti: ^0.7.0
  circular_countdown: ^2.1.0
  introduction_screen: ^3.0.2

  nb_utils: ^4.6.21
  multi_select_flutter: ^4.1.2
  flutter_multi_select_items: ^0.4.2
  path_provider: ^2.0.15
  permission_handler: ^10.1.0
  url_launcher: ^6.1.6
  dio: ^5.3.2
  syncfusion_flutter_pdfviewer: ^20.3.49
  vocsy_epub_viewer: ^1.0.1
  share_plus: ^6.0.0
  flutter:
    sdk: flutter
  device_info_plus: ^8.0.0
  cached_network_image: ^3.2.3
  intl: ^0.17.0
  firebase_auth: ^4.2.0
  google_sign_in: ^5.4.2
  firebase_core: ^2.4.0
  internet_file: ^1.2.0
  flutter_rating_bar: ^4.0.1
  image_picker: ^0.8.6
  getwidget: ^3.0.1
  firebase_messaging: ^14.2.0
  flutter_cashfree_pg_sdk: ^2.0.1+4
  onesignal_flutter: ^3.5.0
  persistent_bottom_nav_bar: ^5.0.2
  overlay_support: ^2.1.0
  morphable_shape: ^1.6.5
  whatsapp_share: ^2.0.1
  screenshot: ^1.3.0
  percent_indicator: ^4.2.3
  sqflite: ^2.2.8+4
  flutter_timer_countdown: ^1.0.5
  flutter_launcher_icons: ^0.13.1
  just_audio: ^0.9.34
  audio_session: ^0.1.15
  rxdart: ^0.27.7
  flutter_html: ^3.0.0-beta.2
  flutter_local_notifications: ^15.1.0+1
  vibration: ^1.7.7
  flutter_windowmanager: ^0.2.0
  json_serializable: ^6.6.2
  share_whatsapp: ^1.0.2


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/social_logo/
    - assets/
    - assets/android_logo/Book_ICON (1).png
    - assets/android_logo/NDN Logo (1).png
    - assets/sample_book.pdf
    - assets/quote_icon.png
    - assets/profile.png
    - assets/Checkmark.gif
    - assets/book_loading.gif
    - assets/onboarding-images/
    - assets/home_screen_images/
    - assets/coaching_logos/
    - assets/coaching_banners/
    - assets/subjects_logo/
    - assets/books_covers/
    - assets/ANCIENT_HISTORY.pdf
    - assets/315_History_Hindi_Lesson5.epub
    - assets/books_testing.epub
    - assets/upsc-exam-timetable-1.jpg
    - assets/book.epub
    - assets/20943863.jpg
    - assets/png-clipart-check-mark-computer-icons-icon-design-cheque-successful-angle-logo.png
    - assets/icons/
    - assets/books_covers/hindi/
  fonts:
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/android_logo/NDN Logo (1).png"
  min_sdk_android: 21 # android min sdk min:16, default 21